const $ = s => document.querySelector(s);
const state = {data:null,country:'中国',decade:'2020年代'};
const cosine=(a,b,features)=>{const av=features.map(k=>a.scores[k]),bv=features.map(k=>b.scores[k]);const dot=av.reduce((s,v,i)=>s+v*bv[i],0),na=Math.sqrt(av.reduce((s,v)=>s+v*v,0)),nb=Math.sqrt(bv.reduce((s,v)=>s+v*v,0));return na&&nb?dot/(na*nb):0};
const pill=(text,cls='')=>`<span class="${cls}">${text}</span>`;
function renderCountries(){const cs=[...new Set(state.data.records.map(r=>r.country))];$('#countries').innerHTML=cs.map(c=>`<button class="${c===state.country?'active':''}" data-country="${c}">${c}</button>`).join('');$('#countryCount').textContent=cs.length;$('#recordCount').textContent=state.data.records.length;document.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>{state.country=b.dataset.country;const rows=state.data.records.filter(r=>r.country===state.country);state.decade=rows.at(-1).decade;renderCountries();renderDecades();render()})}
function renderDecades(){const rows=state.data.records.filter(r=>r.country===state.country);$('#decade').innerHTML=rows.map(r=>`<option ${r.decade===state.decade?'selected':''}>${r.decade}</option>`).join('')}
function render(){const d=state.data,rec=d.records.find(r=>r.country===state.country&&r.decade===state.decade);if(!rec)return;$('#selection').textContent=`${rec.country} · ${rec.decade}`;$('#stageName').textContent=rec.stage;$('#evidence').textContent=rec.evidence;$('#opportunities').innerHTML=[...rec.hotspots,...rec.opportunities].map(x=>pill(x)).join('');$('#risks').innerHTML=rec.risks.map(x=>pill(x)).join('');$('#bars').innerHTML=d.features.map(f=>`<div class="bar"><span>${f}</span><div class="track"><div class="fill" style="width:${rec.scores[f]*20}%"></div></div><b>${rec.scores[f]}</b></div>`).join('');const matches=d.records.filter(r=>r!==rec).map(r=>({r,s:cosine(rec,r,d.features)})).sort((a,b)=>b.s-a.s).slice(0,5);$('#analogues').innerHTML=matches.map((x,i)=>`<div class="analogue"><b>0${i+1}</b><div><strong>${x.r.country} · ${x.r.decade}</strong><small>${x.r.stage}</small></div><span class="score">${(x.s*100).toFixed(1)}%</span></div>`).join('')}
function renderSources(){const labels={'世界银行世界发展指标':'世界银行 · 世界发展指标','Maddison Project Database':'Maddison · 长期经济史数据库','NBER Business Cycle Dating':'NBER · 美国商业周期','IMF World Economic Outlook':'IMF · 世界经济展望','OECD Data Explorer':'OECD · 数据浏览器','UN World Population Prospects':'联合国 · 世界人口展望','中国国家统计局':'中国国家统计局','US Bureau of Economic Analysis':'美国经济分析局'};$('#sourceLinks').innerHTML=state.data.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${labels[s.name]||s.name}</a>`).join('')}
fetch('history-data.json').then(r=>{if(!r.ok)throw Error('数据文件读取失败');return r.json()}).then(d=>{state.data=d;renderCountries();renderDecades();renderSources();render();$('#decade').onchange=e=>{state.decade=e.target.value;render()}}).catch(e=>{$('#stageName').textContent=e.message;$('#evidence').textContent='请通过网站服务器访问本页，而不是直接打开本地 HTML 文件。'});
